version: '3'
services:
  app:
    build: .
    command: ['npm', 'run', 'dev']
    volumes:
      - .:/usr/src/career-day
    ports:
      - '3000:3000'
    environment:
      - DB_USER=postgres
      - DB_DATABASE=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - no-internet
      - internet
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5433:5432'
    networks:
      - no-internet
networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
